import React, { useState, useEffect } from 'react';
import { Plus, ArrowRight, Bell, Download, Map } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import apiClient from '../api/client';
import { socket } from '../services/socket';
import { requestNotificationPermission, triggerSystemNotification } from '../utils/notificationUtils';
import './Dispatch.css';

export const Dispatch: React.FC = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [notifications, setNotifications] = useState<string[]>([]);
  const [trips, setTrips] = useState<any[]>([]);
  const [drivers, setDrivers] = useState<any[]>([]);
  const [trucks, setTrucks] = useState<any[]>([]);
  const [companies, setCompanies] = useState<any[]>([]);
  
  const [formData, setFormData] = useState({
    driverId: '', truckId: '', companyId: '', pickupLocation: '', deliveryLocation: '', loadWeightTons: '', pickupGoogleMapsLink: '', deliveryGoogleMapsLink: ''
  });

  const fetchData = async () => {
    try {
      const [tripsRes, driversRes, trucksRes, companiesRes] = await Promise.all([
        apiClient.get('/trips'),
        apiClient.get('/users/drivers'),
        apiClient.get('/trucks'),
        apiClient.get('/companies')
      ]);
      setTrips(tripsRes.data);
      setDrivers(driversRes.data);
      setTrucks(trucksRes.data);
      setCompanies(companiesRes.data);
    } catch (error) {
      console.error('Failed to fetch dispatch data');
    }
  };

  useEffect(() => {
    fetchData();
    requestNotificationPermission();

    socket.on('status_changed', (data) => {
      const msg = `Trip ${data.tripId} status changed to ${data.status.replace('_', ' ')}`;
      setNotifications(prev => [...prev, msg]);
      
      // Fire Mobile Vibrate & Push Notification
      triggerSystemNotification('V S Transport Update', { body: msg });
      
      fetchData(); // Refresh board on real-time update
    });

    return () => {
      socket.off('status_changed');
    };
  }, []);

  const handleCreateTrip = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await apiClient.post('/trips', {
        ...formData,
        loadWeightTons: Number(formData.loadWeightTons)
      });
      setIsModalOpen(false);
      fetchData();
    } catch (error) {
      alert('Failed to create trip');
    }
  };

  const generateInvoice = (trip: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('V S TRANSPORT INVOICE', 14, 22);
    
    doc.setFontSize(10);
    doc.text(`Invoice Date: ${new Date().toLocaleDateString()}`, 14, 30);
    doc.text(`Trip Number: ${trip.tripNumber}`, 14, 35);
    
    // Bill To
    doc.setFontSize(12);
    doc.text('Bill To:', 14, 50);
    doc.setFontSize(10);
    doc.text(`Company: ${trip.companyId?.name || 'N/A'}`, 14, 56);
    
    // Trip Details Table
    const tableData = [
      ['Truck No.', trip.truckId?.registrationNumber || 'N/A'],
      ['Driver', trip.driverId?.fullName || 'N/A'],
      ['Pickup', trip.pickupLocation],
      ['Destination', trip.deliveryLocation],
      ['Status', trip.status],
      ['Weight (Tons)', trip.loadWeightTons ? `${trip.loadWeightTons} Tons` : 'N/A']
    ];

    autoTable(doc, {
      startY: 65,
      head: [['Description', 'Details']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] },
    });
    
    // Footer
    doc.setFontSize(10);
    doc.text('Generated by V S Transport Automation', 14, (doc as any).lastAutoTable.finalY + 20);

    doc.save(`Invoice_${trip.tripNumber}.pdf`);
  };

  const generateExcelExport = () => {
    // 1. Sheet: Master Data
    const masterData = trips.map(t => ({
      'Trip ID': t.tripNumber,
      'Date Created': new Date(t.createdAt).toLocaleDateString(),
      'Company/Client': t.companyId?.name || 'N/A',
      'Driver Name': t.driverId?.fullName || 'N/A',
      'Truck Reg': t.truckId?.registrationNumber || 'N/A',
      'Pickup': t.pickupLocation,
      'Destination': t.deliveryLocation,
      'Weight (Tons)': t.loadWeightTons || 0,
      'Status': t.status
    }));
    const wsMaster = XLSX.utils.json_to_sheet(masterData);

    // 2. Sheet: Client Summary
    const clientSummary: Record<string, number> = {};
    trips.forEach(t => {
      const cName = t.companyId?.name || 'Unknown';
      clientSummary[cName] = (clientSummary[cName] || 0) + (t.loadWeightTons || 0);
    });
    const clientData = Object.entries(clientSummary).map(([Client, TotalTons]) => ({ Client, 'Total Tons Moved': TotalTons }));
    const wsClient = XLSX.utils.json_to_sheet(clientData);

    // 3. Sheet: Fleet Efficiency
    const fleetSummary: Record<string, number> = {};
    trips.forEach(t => {
      const truck = t.truckId?.registrationNumber || 'Unknown';
      if (t.status === 'COMPLETED' || t.status === 'DELIVERED') {
        fleetSummary[truck] = (fleetSummary[truck] || 0) + 1;
      }
    });
    const fleetData = Object.entries(fleetSummary).map(([Truck, CompletedTrips]) => ({ Truck, 'Completed Trips': CompletedTrips }));
    const wsFleet = XLSX.utils.json_to_sheet(fleetData);

    // Build Workbook
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, wsMaster, 'Master Data');
    XLSX.utils.book_append_sheet(wb, wsClient, 'Client Summary');
    XLSX.utils.book_append_sheet(wb, wsFleet, 'Fleet Efficiency');

    // Export
    XLSX.writeFile(wb, `VS_Transport_Analytics_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  return (
    <div className="dispatch-container">
      <div className="page-header">
        <div>
          <h1 className="page-title">Dispatch & Trips</h1>
          <p className="page-subtitle">Manage all active and past trips</p>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button className="secondary-btn" onClick={generateExcelExport} style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#f8fafc', color: '#0f172a', border: '1px solid #cbd5e1' }}>
            <Download size={18} />
            Export Analytics
          </button>
          <button className="btn-primary" onClick={() => setIsModalOpen(true)}>
            <Plus size={18} />
            Create New Trip
          </button>
        </div>
      </div>

      <div className="trips-board">
        {['ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED'].map((colStatus) => (
          <div key={colStatus} className="status-column">
            <div className="column-header">
              <h3>{colStatus.replace('_', ' ')}</h3>
              <span className="count-badge">
                {trips.filter(t => t.status === colStatus).length}
              </span>
            </div>
            {trips.filter(t => t.status === colStatus).map(trip => (
              <div key={trip._id} className="trip-card">
                <div className="trip-header">
                  <span className="trip-id">{trip.tripNumber}</span>
                  <span className="company-badge">{trip.companyId?.name || 'Client'}</span>
                </div>
                <div className="trip-details">
                  <div className="trip-route">{trip.pickupLocation} <ArrowRight size={14} /> {trip.deliveryLocation}</div>
                  <div className="trip-resource">{trip.truckId?.registrationNumber} • {trip.driverId?.fullName}</div>
                  <div style={{ marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                    {trip.pickupGoogleMapsLink && (
                      <a href={trip.pickupGoogleMapsLink} target="_blank" rel="noreferrer" style={{ fontSize: '12px', color: 'var(--primary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <Map size={12} /> Map: Pickup
                      </a>
                    )}
                    {trip.deliveryGoogleMapsLink && (
                      <a href={trip.deliveryGoogleMapsLink} target="_blank" rel="noreferrer" style={{ fontSize: '12px', color: 'var(--primary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <Map size={12} /> Map: Drop-off
                      </a>
                    )}
                  </div>
                </div>
                {['DELIVERED', 'COMPLETED'].includes(colStatus) && (
                  <button 
                    onClick={() => generateInvoice(trip)} 
                    style={{ marginTop: '12px', padding: '6px 12px', background: '#eef2ff', color: 'var(--primary)', border: 'none', borderRadius: '4px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '12px', width: '100%', justifyContent: 'center', fontWeight: '500' }}
                  >
                    <Download size={14} /> Download Invoice PDF
                  </button>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>

      {notifications.length > 0 && (
        <div className="notification-container" style={{ position: 'fixed', bottom: 20, right: 20, zIndex: 1000, display: 'flex', flexDirection: 'column', gap: 10 }}>
          {notifications.map((msg, i) => (
            <div key={i} style={{ background: 'var(--status-success)', color: '#fff', padding: '12px 20px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: 'var(--shadow-lg)' }}>
              <Bell size={16} /> {msg}
            </div>
          ))}
        </div>
      )}

      {isModalOpen && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h2>Create New Trip</h2>
              <button className="close-btn" onClick={() => setIsModalOpen(false)}>&times;</button>
            </div>
            <form onSubmit={handleCreateTrip}>
              <div className="form-group">
                <label>Company/Client</label>
                <select required value={formData.companyId} onChange={e => setFormData({...formData, companyId: e.target.value})}>
                  <option value="">Select Company</option>
                  {companies.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}
                </select>
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Assign Truck</label>
                  <select required value={formData.truckId} onChange={e => setFormData({...formData, truckId: e.target.value})}>
                    <option value="">Select Truck</option>
                    {trucks.map(t => <option key={t._id} value={t._id}>{t.registrationNumber}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label>Assign Driver</label>
                  <select required value={formData.driverId} onChange={e => setFormData({...formData, driverId: e.target.value})}>
                    <option value="">Select Driver</option>
                    {drivers.map(d => <option key={d._id} value={d._id}>{d.fullName}</option>)}
                  </select>
                </div>
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Pickup Location</label>
                  <input required type="text" placeholder="e.g. Rohtak Plant" value={formData.pickupLocation} onChange={e => setFormData({...formData, pickupLocation: e.target.value})} />
                </div>
                <div className="form-group">
                  <label>Drop-off Location</label>
                  <input required type="text" placeholder="e.g. Jaipur Godown" value={formData.deliveryLocation} onChange={e => setFormData({...formData, deliveryLocation: e.target.value})} />
                </div>
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Pickup Google Maps Link</label>
                  <input type="url" placeholder="https://maps.google.com/..." value={formData.pickupGoogleMapsLink} onChange={e => setFormData({...formData, pickupGoogleMapsLink: e.target.value})} />
                </div>
                <div className="form-group">
                  <label>Drop-off Google Maps Link</label>
                  <input type="url" placeholder="https://maps.google.com/..." value={formData.deliveryGoogleMapsLink} onChange={e => setFormData({...formData, deliveryGoogleMapsLink: e.target.value})} />
                </div>
              </div>
              <div className="form-group">
                <label>Load Weight (Tons)</label>
                <input required type="number" placeholder="e.g. 40" value={formData.loadWeightTons} onChange={e => setFormData({...formData, loadWeightTons: e.target.value})} />
              </div>
              
              <div className="modal-actions">
                <button type="button" className="secondary-btn" onClick={() => setIsModalOpen(false)}>Cancel</button>
                <button type="submit" className="primary-btn">Create & Dispatch</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
